const a = "Score"
const b ="0"
const c = "Level"
const d = "1"
const e = "Start"
const f = "Restart"
const g = "Terminate"
document.getElementById("scoreText").innerHTML = a;
document.getElementById("score").innerHTML = b;
document.getElementById("levelText").innerHTML = c;
document.getElementById("level").innerHTML = d;
document.getElementById("startBtn").innerHTML = e;
document.getElementById("restartBtn").innerHTML = f;
document.getElementById("terminateBtn").innerHTML = g;